services:
  # --- Web API ---
  - type: web
    name: line-crypto-hourly-news
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false   # กำหนดใน Dashboard
      - key: LINE_USER_ID
        sync: false   # กำหนดใน Dashboard

cronJobs:
  # 🔔 สแกนสัญญาณทุก 5 นาที
  - name: intraday-scan-every-5m
    schedule: "*/5 * * * *"
    command: python jobs/scan_once.py
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
      - key: MTA_SYMBOLS
        value: "BTCUSDT"

  # 🛡️ กันหลับ → ยิง health check web ทุก 5 นาที
  - name: keepalive
    schedule: "*/5 * * * *"
    command: curl -m 5 -sS https://line-crypto-hourly-news.onrender.com/health || true
