services:
  - type: web
    name: line-crypto-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: PRICE_PROVIDER
        value: binance
      - key: QUOTE_ASSET
        value: USDT
      - key: PRICE_TTL_SECONDS
        value: "15"
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false

  - type: worker
    name: line-crypto-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. python worker.py
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: PRICE_PROVIDER
        value: binance
      - key: QUOTE_ASSET
        value: USDT
      - key: PRICE_TTL_SECONDS
        value: "15"
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
