services:
  - type: web
    name: line-crypto-hourly-news
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false   # ใส่ค่าใน Dashboard หลังจากนี้
