services:
  - type: web
    name: line-crypto-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: PRICE_PROVIDER
        value: binance
      - key: QUOTE_ASSET
        value: USDT
      - key: PRICE_TTL_SECONDS
        value: "15"
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false

  - type: worker
    name: line-crypto-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. python worker.py
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: PRICE_PROVIDER
        value: binance
      - key: QUOTE_ASSET
        value: USDT
      - key: PRICE_TTL_SECONDS
        value: "15"
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false

  # ----- Cron 1: แจ้ง "ราคาเร็ว" ทุกชั่วโมง (UTC top of hour) -----
  - type: cron
    name: line-crypto-hourly-btc-price
    env: python
    plan: free
    schedule: "0 * * * *"   # ทุกชั่วโมง นาทีที่ 00 (UTC)
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. python scripts/push_price_hourly.py
    envVars:
      - key: ENV
        value: production
      - key: QUOTE_ASSET
        value: USDT
      - key: PRICE_SYMBOL
        value: BTCUSDT
      - key: JOB_BROADCAST
        value: "1"           # broadcast ให้ทุกคน (ไม่ใช้ LINE_DEFAULT_TO)
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false

  # ----- Cron 2: แจ้ง "สรุปวิเคราะห์" ทุกชั่วโมง (โปรไฟล์ baseline, TF=1H) -----
  - type: cron
    name: line-crypto-hourly-btc-analysis
    env: python
    plan: free
    schedule: "0 * * * *"   # ทุกชั่วโมง นาทีที่ 00 (UTC)
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. python -m jobs.push_btc_hourly
    envVars:
      - key: ENV
        value: production
      - key: JOB_SYMBOL
        value: BTCUSDT
      - key: JOB_TF
        value: 1H
      - key: STRATEGY_PROFILE
        value: baseline
      - key: JOB_BROADCAST
        value: "1"
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
