services:
  - type: web
    name: line-crypto-hourly-news
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false   # ใส่ค่าใน Dashboard หลังจากนี้

# --- Cron job: push news 08:00 ICT (01:00 UTC) ---
services:
  - type: cron
    name: line-crypto-hourly-news-8am
    env: python
    schedule: "0 1 * * *"   # 01:00 UTC = 08:00 Asia/Bangkok
    buildCommand: pip install -r requirements.txt
    startCommand: python jobs/push_news.py --max-items 6 --limit-per-source 3
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false   # ใส่ค่าใน Render Dashboard
      - key: TRANSLATOR_PROVIDER
        value: "fallback"   # เปลี่ยนเป็น google/deepl/openai ถ้าตั้งค่า API key แล้ว
# --- เพิ่มด้านล่างไฟล์ render.yaml ---
cronJobs:
  - name: keepalive
    schedule: "*/5 * * * *"   # ทุก 5 นาที
    command: |
      curl -m 5 -sS https://<YOUR-SERVICE>.onrender.com/health || true
