# app/config/risk.yaml
# =============================================================================
# Risk Configuration (ready-to-use)
# =============================================================================
version: 1

account:
  base_currency: USD
  balance_mode: static        # static | dynamic
  starting_balance: 10000.0

risk_per_trade:
  r_percent: 1.0
  max_concurrent_positions: 3
  max_daily_loss_percent: 5.0
  max_weekly_loss_percent: 12.0

reward:
  rr: 1.5
  # ✅ กำหนด TP แบบ % 3/5/7
  partial_take_profit:
    enabled: true
    levels:
      - { pct: 0.33, tp_pct: 0.03 }  # TP1 +3%
      - { pct: 0.33, tp_pct: 0.05 }  # TP2 +5%
      - { pct: 0.34, tp_pct: 0.07 }  # TP3 +7%

stop_loss:
  mode: fixed_pct              # ใช้ SL เป็น % คงที่
  atr:
    length: 14
    mult: 1.0
  fixed_pct:
    percent: 3.0               # ✅ SL = -3%
  structure:
    swing_lookback: 10
  trailing:
    enabled: true
    type: atr
    atr_mult: 1.0
    percent: 1.0
    step_lock: true

position_sizing:
  method: risk_percent
  fixed_size:
    qty: 1.0
  notional_usd:
    amount: 500.0
  min_position_notional: 50.0
  max_position_notional: 3000.0
  pyramiding:
    enabled: false
    max_adds: 2
    add_trigger_rr: 1.0

execution:
  slippage_bps: 5
  taker_fee_bps: 7
  maker_fee_bps: 2
  leverage:
    enabled: false
    max_leverage: 3

hygiene:
  cooldown_sec: 30
  no_flip_until_exit: true
  session_limit:
    enabled: false
    allowed: "24/7"

alerts:
  move_thresholds_pct: [1.0, 2.0]
  throttle_sec: 60

time_exit:
  enabled: false
  max_bars_hold: 300
