# ====== LINE BOT CONFIG ======
LINE_CHANNEL_SECRET=5ff2d689dc8f9c4ac7d45a5a20ce11c3
LINE_CHANNEL_ACCESS_TOKEN=YCvky4EDwOvZmzyw9ChiYpBLY4MvFqZZ+a9vC2Nt5mhhw3UQoRUQSw/hJIjtWoxtxnoOLHRevaI9g3sxhNpQlyW5Xkdhw51/jwVAVoPGhoFPUz8Xz9HfxJYRWQNr0YvTXhFoJlxe1+lNbnTUGBGzRgdB04t89/1O/w1cDnyilFU=

# ====== PYTHON CONFIG ======
PYTHONPATH=.

# ====== ALERT CONFIG ======
ALERT_ENABLED=true
ALERT_THRESHOLD_PCT=5
ALERT_POLL_SEC=60
ALERT_COOLDOWN_SEC=1800
ALERT_HYSTERESIS_PCT=1.0
ALERT_SYMBOL=BTC
